# encoding: utf-8
class Senator
  include ActiveModel::Validations
  include ActiveModel::Dirty

  attr_accessor :id, :name, :street1, :street2, :city, :state, :postalcode, :home_state, :name_and_party

  def self.all
    i = 0
    hash_all.map do |s|
      id          = i = i+1
      name        = [s['first_name'], s['last_name']].join(" ")
      address     = s['address'].split
      postalcode  = address.pop
      state       = address.pop
      city        = address.pop.capitalize
      street1     = address.join(" ").capitalize
      home_state  = s['state']

      senator                     = Senator.new
      senator.id                  = id
      senator.name                = name
      senator.street1             = street1
      senator.street2             = " "
      senator.city                = city
      senator.state               = state
      senator.postalcode          = postalcode
      senator.home_state          = home_state
      senator.name_and_party      = [name, "(#{s['party']})"].join(" ")

      senator
    end.sort_by(&:home_state)
  end

  def self.hash_all
    [
      {
        "member_full" => "Akaka (D-HI)",
        "last_name" => "Akaka",
        "first_name" => "Daniel K.",
        "party" => "D",
        "state" => "HI",
        "address" => "141 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6361",
        "email" => "http://www.akaka.senate.gov/email-senator-akaka.cfm",
        "website" => "http://www.akaka.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "A000069"
      },
      {
        "member_full" => "Alexander (R-TN)",
        "last_name" => "Alexander",
        "first_name" => "Lamar",
        "party" => "R",
        "state" => "TN",
        "address" => "455 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4944",
        "email" => "http://www.alexander.senate.gov/public/index.cfm?p=Email",
        "website" => "http://www.alexander.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "A000360"
      },
      {
        "member_full" => "Ayotte (R-NH)",
        "last_name" => "Ayotte",
        "first_name" => "Kelly",
        "party" => "R",
        "state" => "NH",
        "address" => "144 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3324",
        "email" => "http://www.ayotte.senate.gov/?p=contact",
        "website" => "http://www.ayotte.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "A000368"
      },
      {
        "member_full" => "Barrasso (R-WY)",
        "last_name" => "Barrasso",
        "first_name" => "John",
        "party" => "R",
        "state" => "WY",
        "address" => "307 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6441",
        "email" => "http://www.barrasso.senate.gov/public/index.cfm?FuseAction=ContactUs.ContactForm",
        "website" => "http://www.barrasso.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "B001261"
      },
      {
        "member_full" => "Baucus (D-MT)",
        "last_name" => "Baucus",
        "first_name" => "Max",
        "party" => "D",
        "state" => "MT",
        "address" => "511 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2651",
        "email" => "http://www.baucus.senate.gov/contact/emailForm.cfm?subj=issue",
        "website" => "http://www.baucus.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "B000243"
      },
      {
        "member_full" => "Begich (D-AK)",
        "last_name" => "Begich",
        "first_name" => "Mark",
        "party" => "D",
        "state" => "AK",
        "address" => "111 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3004",
        "email" => "http://www.begich.senate.gov/public/index.cfm?p=EmailSenator",
        "website" => "http://www.begich.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "B001265"
      },
      {
        "member_full" => "Bennet (D-CO)",
        "last_name" => "Bennet",
        "first_name" => "Michael F.",
        "party" => "D",
        "state" => "CO",
        "address" => "458 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5852",
        "email" => "http://www.bennet.senate.gov/contact/",
        "website" => "http://www.bennet.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "B001267"
      },
      {
        "member_full" => "Bingaman (D-NM)",
        "last_name" => "Bingaman",
        "first_name" => "Jeff",
        "party" => "D",
        "state" => "NM",
        "address" => "703 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5521",
        "email" => "http://www.bingaman.senate.gov/contact/",
        "website" => "http://www.bingaman.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "B000468"
      },
      {
        "member_full" => "Blumenthal (D-CT)",
        "last_name" => "Blumenthal",
        "first_name" => "Richard",
        "party" => "D",
        "state" => "CT",
        "address" => "702 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2823",
        "email" => "http://www.blumenthal.senate.gov/contact/",
        "website" => "http://www.blumenthal.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "B001277"
      },
      {
        "member_full" => "Blunt (R-MO)",
        "last_name" => "Blunt",
        "first_name" => "Roy",
        "party" => "R",
        "state" => "MO",
        "address" => "260 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5721",
        "email" => "http://www.blunt.senate.gov/public/index.cfm/contact-form?p=contact-roy",
        "website" => "http://www.blunt.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "B000575"
      },
      {
        "member_full" => "Boozman (R-AR)",
        "last_name" => "Boozman",
        "first_name" => "John",
        "party" => "R",
        "state" => "AR",
        "address" => "320 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4843",
        "email" => "http://www.boozman.senate.gov/public/index.cfm/e-mail-me",
        "website" => "http://www.boozman.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "B001236"
      },
      {
        "member_full" => "Boxer (D-CA)",
        "last_name" => "Boxer",
        "first_name" => "Barbara",
        "party" => "D",
        "state" => "CA",
        "address" => "112 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3553",
        "email" => "http://www.boxer.senate.gov/en/contact/",
        "website" => "http://www.boxer.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "B000711"
      },
      {
        "member_full" => "Brown (R-MA)",
        "last_name" => "Brown",
        "first_name" => "Scott P.",
        "party" => "R",
        "state" => "MA",
        "address" => "359 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4543",
        "email" => "http://www.scottbrown.senate.gov/public/index.cfm/emailscottbrown",
        "website" => "http://www.scottbrown.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "B001268"
      },
      {
        "member_full" => "Brown (D-OH)",
        "last_name" => "Brown",
        "first_name" => "Sherrod",
        "party" => "D",
        "state" => "OH",
        "address" => "713 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2315",
        "email" => "http://www.brown.senate.gov/contact/",
        "website" => "http://www.brown.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "B000944"
      },
      {
        "member_full" => "Burr (R-NC)",
        "last_name" => "Burr",
        "first_name" => "Richard",
        "party" => "R",
        "state" => "NC",
        "address" => "217 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3154",
        "email" => "http://www.burr.senate.gov/public/index.cfm?FuseAction=Contact.ContactForm",
        "website" => "http://www.burr.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "B001135"
      },
      {
        "member_full" => "Cantwell (D-WA)",
        "last_name" => "Cantwell",
        "first_name" => "Maria",
        "party" => "D",
        "state" => "WA",
        "address" => "311 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3441",
        "email" => "http://www.cantwell.senate.gov/public/index.cfm/email-maria",
        "website" => "http://www.cantwell.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "C000127"
      },
      {
        "member_full" => "Cardin (D-MD)",
        "last_name" => "Cardin",
        "first_name" => "Benjamin L.",
        "party" => "D",
        "state" => "MD",
        "address" => "509 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4524",
        "email" => "http://www.cardin.senate.gov/contact/",
        "website" => "http://www.cardin.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "C000141"
      },
      {
        "member_full" => "Carper (D-DE)",
        "last_name" => "Carper",
        "first_name" => "Thomas R.",
        "party" => "D",
        "state" => "DE",
        "address" => "513 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2441",
        "email" => "http://carper.senate.gov/public/index.cfm/email-senator-carper",
        "website" => "http://www.carper.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "C000174"
      },
      {
        "member_full" => "Casey (D-PA)",
        "last_name" => "Casey",
        "first_name" => "Robert P., Jr.",
        "party" => "D",
        "state" => "PA",
        "address" => "393 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6324",
        "email" => "http://www.casey.senate.gov/contact/",
        "website" => "http://www.casey.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "C001070"
      },
      {
        "member_full" => "Chambliss (R-GA)",
        "last_name" => "Chambliss",
        "first_name" => "Saxby",
        "party" => "R",
        "state" => "GA",
        "address" => "416 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3521",
        "email" => "http://www.chambliss.senate.gov/public/index.cfm?p=Email",
        "website" => "http://www.chambliss.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "C000286"
      },
      {
        "member_full" => "Coats (R-IN)",
        "last_name" => "Coats",
        "first_name" => "Daniel",
        "party" => "R",
        "state" => "IN",
        "address" => "493 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5623",
        "email" => "http://www.coats.senate.gov/contact/",
        "website" => "http://www.coats.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "C000542"
      },
      {
        "member_full" => "Coburn (R-OK)",
        "last_name" => "Coburn",
        "first_name" => "Tom",
        "party" => "R",
        "state" => "OK",
        "address" => "172 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5754",
        "email" => "http://www.coburn.senate.gov/public/index.cfm/contactsenatorcoburn?p=ContactForm",
        "website" => "http://www.coburn.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "C000560"
      },
      {
        "member_full" => "Cochran (R-MS)",
        "last_name" => "Cochran",
        "first_name" => "Thad",
        "party" => "R",
        "state" => "MS",
        "address" => "113 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5054",
        "email" => "http://www.cochran.senate.gov/email.html",
        "website" => "http://www.cochran.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "C000567"
      },
      {
        "member_full" => "Collins (R-ME)",
        "last_name" => "Collins",
        "first_name" => "Susan M.",
        "party" => "R",
        "state" => "ME",
        "address" => "413 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2523",
        "email" => "http://www.collins.senate.gov/public/continue.cfm?FuseAction=ContactSenatorCollins.EmailIssue",
        "website" => "http://www.collins.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "C001035"
      },
      {
        "member_full" => "Conrad (D-ND)",
        "last_name" => "Conrad",
        "first_name" => "Kent",
        "party" => "D",
        "state" => "ND",
        "address" => "530 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2043",
        "email" => "http://www.conrad.senate.gov/contact/webform.cfm",
        "website" => "http://www.conrad.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "C000705"
      },
      {
        "member_full" => "Coons (D-DE)",
        "last_name" => "Coons",
        "first_name" => "Christopher A.",
        "party" => "D",
        "state" => "DE",
        "address" => "127A RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5042",
        "email" => "http://www.coons.senate.gov/contact/",
        "website" => "http://www.coons.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "C001088"
      },
      {
        "member_full" => "Corker (R-TN)",
        "last_name" => "Corker",
        "first_name" => "Bob",
        "party" => "R",
        "state" => "TN",
        "address" => "185 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3344",
        "email" => "http://www.corker.senate.gov/public/index.cfm?p=ContactMe",
        "website" => "http://www.corker.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "C001071"
      },
      {
        "member_full" => "Cornyn (R-TX)",
        "last_name" => "Cornyn",
        "first_name" => "John",
        "party" => "R",
        "state" => "TX",
        "address" => "517 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2934",
        "email" => "http://www.cornyn.senate.gov/public/index.cfm?p=ContactForm",
        "website" => "http://www.cornyn.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "C001056"
      },
      {
        "member_full" => "Crapo (R-ID)",
        "last_name" => "Crapo",
        "first_name" => "Mike",
        "party" => "R",
        "state" => "ID",
        "address" => "239 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6142",
        "email" => "http://www.crapo.senate.gov/contact/email.cfm",
        "website" => "http://www.crapo.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "C000880"
      },
      {
        "member_full" => "DeMint (R-SC)",
        "last_name" => "DeMint",
        "first_name" => "Jim",
        "party" => "R",
        "state" => "SC",
        "address" => "167 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6121",
        "email" => "http://www.demint.senate.gov/public/index.cfm?p=ContactInformation",
        "website" => "http://www.demint.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "D000595"
      },
      {
        "member_full" => "Durbin (D-IL)",
        "last_name" => "Durbin",
        "first_name" => "Richard J.",
        "party" => "D",
        "state" => "IL",
        "address" => "711 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2152",
        "email" => "http://www.durbin.senate.gov/public/index.cfm/contact",
        "website" => "http://www.durbin.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "D000563",
        "leadership_position" => "Assistant Majority Leader"
      },
      {
        "member_full" => "Enzi (R-WY)",
        "last_name" => "Enzi",
        "first_name" => "Michael B.",
        "party" => "R",
        "state" => "WY",
        "address" => "379A RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3424",
        "email" => "http://www.enzi.senate.gov/public/index.cfm/contact?p=e-mail-senator-enzi",
        "website" => "http://www.enzi.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "E000285"
      },
      {
        "member_full" => "Feinstein (D-CA)",
        "last_name" => "Feinstein",
        "first_name" => "Dianne",
        "party" => "D",
        "state" => "CA",
        "address" => "331 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3841",
        "email" => "http://www.feinstein.senate.gov/public/index.cfm/e-mail-me",
        "website" => "http://www.feinstein.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "F000062"
      },
      {
        "member_full" => "Franken (D-MN)",
        "last_name" => "Franken",
        "first_name" => "Al",
        "party" => "D",
        "state" => "MN",
        "address" => "309 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5641",
        "email" => "http://www.franken.senate.gov/?p=contact",
        "website" => "http://www.franken.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "F000457"
      },
      {
        "member_full" => "Gillibrand (D-NY)",
        "last_name" => "Gillibrand",
        "first_name" => "Kirsten E.",
        "party" => "D",
        "state" => "NY",
        "address" => "478 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4451",
        "email" => "http://www.gillibrand.senate.gov/contact/",
        "website" => "http://www.gillibrand.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "G000555"
      },
      {
        "member_full" => "Graham (R-SC)",
        "last_name" => "Graham",
        "first_name" => "Lindsey",
        "party" => "R",
        "state" => "SC",
        "address" => "290 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5972",
        "email" => "http://www.lgraham.senate.gov/public/index.cfm?FuseAction=Contact.EmailSenatorGraham",
        "website" => "http://www.lgraham.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "G000359"
      },
      {
        "member_full" => "Grassley (R-IA)",
        "last_name" => "Grassley",
        "first_name" => "Chuck",
        "party" => "R",
        "state" => "IA",
        "address" => "135 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3744",
        "email" => "http://www.grassley.senate.gov/contact.cfm",
        "website" => "http://www.grassley.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "G000386"
      },
      {
        "member_full" => "Hagan (D-NC)",
        "last_name" => "Hagan",
        "first_name" => "Kay R.",
        "party" => "D",
        "state" => "NC",
        "address" => "521 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6342",
        "email" => "http://www.hagan.senate.gov/?p=contact",
        "website" => "http://www.hagan.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "H001049"
      },
      {
        "member_full" => "Harkin (D-IA)",
        "last_name" => "Harkin",
        "first_name" => "Tom",
        "party" => "D",
        "state" => "IA",
        "address" => "731 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3254",
        "email" => "http://www.harkin.senate.gov/contact.cfm",
        "website" => "http://www.harkin.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "H000206"
      },
      {
        "member_full" => "Hatch (R-UT)",
        "last_name" => "Hatch",
        "first_name" => "Orrin G.",
        "party" => "R",
        "state" => "UT",
        "address" => "104 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5251",
        "email" => "http://www.hatch.senate.gov/public/index.cfm/contact?p=Email-Orrin",
        "website" => "http://www.hatch.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "H000338"
      },
      {
        "member_full" => "Heller (R-NV)",
        "last_name" => "Heller",
        "first_name" => "Dean",
        "party" => "R",
        "state" => "NV",
        "address" => "361A RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6244",
        "email" => "http://www.heller.senate.gov/public/index.cfm/contact-form",
        "website" => "http://www.heller.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "H001041"
      },
      {
        "member_full" => "Hoeven (R-ND)",
        "last_name" => "Hoeven",
        "first_name" => "John",
        "party" => "R",
        "state" => "ND",
        "address" => "120 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2551",
        "email" => "http://www.hoeven.senate.gov/public/index.cfm/email-the-senator",
        "website" => "http://www.hoeven.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "H001061"
      },
      {
        "member_full" => "Hutchison (R-TX)",
        "last_name" => "Hutchison",
        "first_name" => "Kay Bailey",
        "party" => "R",
        "state" => "TX",
        "address" => "284 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5922",
        "email" => "http://www.hutchison.senate.gov/?p=email_kay",
        "website" => "http://www.hutchison.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "H001016"
      },
      {
        "member_full" => "Inhofe (R-OK)",
        "last_name" => "Inhofe",
        "first_name" => "James M.",
        "party" => "R",
        "state" => "OK",
        "address" => "205 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4721",
        "email" => "http://www.inhofe.senate.gov/public/index.cfm?FuseAction=Contact.ContactForm",
        "website" => "http://www.inhofe.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "I000024"
      },
      {
        "member_full" => "Inouye (D-HI)",
        "last_name" => "Inouye",
        "first_name" => "Daniel K.",
        "party" => "D",
        "state" => "HI",
        "address" => "722 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3934",
        "email" => "http://www.inouye.senate.gov/Contact/ContactDKI.cfm",
        "website" => "http://www.inouye.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "I000025"
      },
      {
        "member_full" => "Isakson (R-GA)",
        "last_name" => "Isakson",
        "first_name" => "Johnny",
        "party" => "R",
        "state" => "GA",
        "address" => "131 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3643",
        "email" => "http://www.isakson.senate.gov/contact.cfm",
        "website" => "http://www.isakson.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "I000055"
      },
      {
        "member_full" => "Johanns (R-NE)",
        "last_name" => "Johanns",
        "first_name" => "Mike",
        "party" => "R",
        "state" => "NE",
        "address" => "404 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4224",
        "email" => "http://www.johanns.senate.gov/public/?p=ContactSenatorJohanns",
        "website" => "http://www.johanns.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "J000291"
      },
      {
        "member_full" => "Johnson (R-WI)",
        "last_name" => "Johnson",
        "first_name" => "Ron",
        "party" => "R",
        "state" => "WI",
        "address" => "386 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5323",
        "email" => "http://www.ronjohnson.senate.gov/public/index.cfm/contact",
        "website" => "http://www.ronjohnson.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "J000293"
      },
      {
        "member_full" => "Johnson (D-SD)",
        "last_name" => "Johnson",
        "first_name" => "Tim",
        "party" => "D",
        "state" => "SD",
        "address" => "136 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5842",
        "email" => "http://www.johnson.senate.gov/public/index.cfm?p=Contact",
        "website" => "http://www.johnson.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "J000177"
      },
      {
        "member_full" => "Kerry (D-MA)",
        "last_name" => "Kerry",
        "first_name" => "John F.",
        "party" => "D",
        "state" => "MA",
        "address" => "218 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2742",
        "email" => "http://www.kerry.senate.gov/contact/",
        "website" => "http://www.kerry.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "K000148"
      },
      {
        "member_full" => "Kirk (R-IL)",
        "last_name" => "Kirk",
        "first_name" => "Mark",
        "party" => "R",
        "state" => "IL",
        "address" => "524 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2854",
        "email" => "http://www.kirk.senate.gov/?p=contact",
        "website" => "http://www.kirk.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "K000360"
      },
      {
        "member_full" => "Klobuchar (D-MN)",
        "last_name" => "Klobuchar",
        "first_name" => "Amy",
        "party" => "D",
        "state" => "MN",
        "address" => "302 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3244",
        "email" => "http://www.klobuchar.senate.gov/emailamy.cfm",
        "website" => "http://www.klobuchar.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "K000367"
      },
      {
        "member_full" => "Kohl (D-WI)",
        "last_name" => "Kohl",
        "first_name" => "Herb",
        "party" => "D",
        "state" => "WI",
        "address" => "330 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5653",
        "email" => "http://www.kohl.senate.gov/contact.cfm",
        "website" => "http://www.kohl.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "K000305"
      },
      {
        "member_full" => "Kyl (R-AZ)",
        "last_name" => "Kyl",
        "first_name" => "Jon",
        "party" => "R",
        "state" => "AZ",
        "address" => "730 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4521",
        "email" => "http://www.kyl.senate.gov/contact.cfm",
        "website" => "http://www.kyl.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "K000352",
        "leadership_position" => "Assistant Minority Leader"
      },
      {
        "member_full" => "Landrieu (D-LA)",
        "last_name" => "Landrieu",
        "first_name" => "Mary L.",
        "party" => "D",
        "state" => "LA",
        "address" => "431 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5824",
        "email" => "http://www.landrieu.senate.gov/?p=contact",
        "website" => "http://www.landrieu.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "L000550"
      },
      {
        "member_full" => "Lautenberg (D-NJ)",
        "last_name" => "Lautenberg",
        "first_name" => "Frank R.",
        "party" => "D",
        "state" => "NJ",
        "address" => "324 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3224",
        "email" => "http://www.lautenberg.senate.gov/contact/routing.cfm",
        "website" => "http://www.lautenberg.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "L000123"
      },
      {
        "member_full" => "Leahy (D-VT)",
        "last_name" => "Leahy",
        "first_name" => "Patrick J.",
        "party" => "D",
        "state" => "VT",
        "address" => "437 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4242",
        "email" => "http://www.leahy.senate.gov/contact/",
        "website" => "http://www.leahy.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "L000174"
      },
      {
        "member_full" => "Lee (R-UT)",
        "last_name" => "Lee",
        "first_name" => "Mike",
        "party" => "R",
        "state" => "UT",
        "address" => "316 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5444",
        "email" => "http://www.lee.senate.gov/public/index.cfm/contact",
        "website" => "http://www.lee.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "L000577"
      },
      {
        "member_full" => "Levin (D-MI)",
        "last_name" => "Levin",
        "first_name" => "Carl",
        "party" => "D",
        "state" => "MI",
        "address" => "269 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6221",
        "email" => "http://www.levin.senate.gov/contact/",
        "website" => "http://www.levin.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "L000261"
      },
      {
        "member_full" => "Lieberman (ID-CT)",
        "last_name" => "Lieberman",
        "first_name" => "Joseph I.",
        "party" => "ID",
        "state" => "CT",
        "address" => "706 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4041",
        "email" => "http://www.lieberman.senate.gov/index.cfm/contact/email-me-about-an-issue",
        "website" => "http://www.lieberman.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "L000304"
      },
      {
        "member_full" => "Lugar (R-IN)",
        "last_name" => "Lugar",
        "first_name" => "Richard G.",
        "party" => "R",
        "state" => "IN",
        "address" => "306 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4814",
        "email" => "http://www.lugar.senate.gov/contact/",
        "website" => "http://www.lugar.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "L000504"
      },
      {
        "member_full" => "Manchin (D-WV)",
        "last_name" => "Manchin",
        "first_name" => "Joe, III",
        "party" => "D",
        "state" => "WV",
        "address" => "303 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3954",
        "email" => "http://www.manchin.senate.gov/public/index.cfm/contact-form",
        "website" => "http://www.manchin.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "M001183"
      },
      {
        "member_full" => "McCain (R-AZ)",
        "last_name" => "McCain",
        "first_name" => "John",
        "party" => "R",
        "state" => "AZ",
        "address" => "241 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2235",
        "email" => "http://www.mccain.senate.gov/public/index.cfm?FuseAction=Contact.ContactForm",
        "website" => "http://www.mccain.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "M000303"
      },
      {
        "member_full" => "McCaskill (D-MO)",
        "last_name" => "McCaskill",
        "first_name" => "Claire",
        "party" => "D",
        "state" => "MO",
        "address" => "506 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6154",
        "email" => "http://www.mccaskill.senate.gov/?p=contact",
        "website" => "http://www.mccaskill.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "M001170"
      },
      {
        "member_full" => "McConnell (R-KY)",
        "last_name" => "McConnell",
        "first_name" => "Mitch",
        "party" => "R",
        "state" => "KY",
        "address" => "317 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2541",
        "email" => "http://www.mcconnell.senate.gov/public/index.cfm?p=contact",
        "website" => "http://www.mcconnell.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "M000355",
        "leadership_position" => "Minority Leader"
      },
      {
        "member_full" => "Menendez (D-NJ)",
        "last_name" => "Menendez",
        "first_name" => "Robert",
        "party" => "D",
        "state" => "NJ",
        "address" => "528 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4744",
        "email" => "http://menendez.senate.gov/contact/",
        "website" => "http://menendez.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "M000639"
      },
      {
        "member_full" => "Merkley (D-OR)",
        "last_name" => "Merkley",
        "first_name" => "Jeff",
        "party" => "D",
        "state" => "OR",
        "address" => "313 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3753",
        "email" => "http://www.merkley.senate.gov/contact/",
        "website" => "http://www.merkley.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "M001176"
      },
      {
        "member_full" => "Mikulski (D-MD)",
        "last_name" => "Mikulski",
        "first_name" => "Barbara A.",
        "party" => "D",
        "state" => "MD",
        "address" => "503 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4654",
        "email" => "http://www.mikulski.senate.gov/contact/",
        "website" => "http://www.mikulski.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "M000702"
      },
      {
        "member_full" => "Moran (R-KS)",
        "last_name" => "Moran",
        "first_name" => "Jerry",
        "party" => "R",
        "state" => "KS",
        "address" => "354 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6521",
        "email" => "http://www.moran.senate.gov/public/index.cfm?p=e-mail-jerry",
        "website" => "http://www.moran.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "M000934"
      },
      {
        "member_full" => "Murkowski (R-AK)",
        "last_name" => "Murkowski",
        "first_name" => "Lisa",
        "party" => "R",
        "state" => "AK",
        "address" => "709 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6665",
        "email" => "http://www.murkowski.senate.gov/public/index.cfm?p=Contact",
        "website" => "http://www.murkowski.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "M001153"
      },
      {
        "member_full" => "Murray (D-WA)",
        "last_name" => "Murray",
        "first_name" => "Patty",
        "party" => "D",
        "state" => "WA",
        "address" => "448 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2621",
        "email" => "http://www.murray.senate.gov/email/index.cfm",
        "website" => "http://www.murray.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "M001111"
      },
      {
        "member_full" => "Nelson (D-NE)",
        "last_name" => "Nelson",
        "first_name" => "Ben",
        "party" => "D",
        "state" => "NE",
        "address" => "720 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6551",
        "email" => "http://www.bennelson.senate.gov/contact-me.cfm",
        "website" => "http://www.bennelson.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "N000180"
      },
      {
        "member_full" => "Nelson (D-FL)",
        "last_name" => "Nelson",
        "first_name" => "Bill",
        "party" => "D",
        "state" => "FL",
        "address" => "716 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5274",
        "email" => "http://www.billnelson.senate.gov/contact/index.cfm",
        "website" => "http://www.billnelson.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "N000032"
      },
      {
        "member_full" => "Paul (R-KY)",
        "last_name" => "Paul",
        "first_name" => "Rand",
        "party" => "R",
        "state" => "KY",
        "address" => "208 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4343",
        "email" => "http://www.paul.senate.gov/?p=contact",
        "website" => "http://www.paul.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "P000603"
      },
      {
        "member_full" => "Portman (R-OH)",
        "last_name" => "Portman",
        "first_name" => "Rob",
        "party" => "R",
        "state" => "OH",
        "address" => "338 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3353",
        "email" => "http://www.portman.senate.gov/public/index.cfm/contact?p=contact-form",
        "website" => "http://www.portman.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "P000449"
      },
      {
        "member_full" => "Pryor (D-AR)",
        "last_name" => "Pryor",
        "first_name" => "Mark L.",
        "party" => "D",
        "state" => "AR",
        "address" => "255 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2353",
        "email" => "http://www.pryor.senate.gov/public/index.cfm?p=ContactMe",
        "website" => "http://www.pryor.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "P000590"
      },
      {
        "member_full" => "Reed (D-RI)",
        "last_name" => "Reed",
        "first_name" => "Jack",
        "party" => "D",
        "state" => "RI",
        "address" => "728 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4642",
        "email" => "http://www.reed.senate.gov/contact/",
        "website" => "http://www.reed.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "R000122"
      },
      {
        "member_full" => "Reid (D-NV)",
        "last_name" => "Reid",
        "first_name" => "Harry",
        "party" => "D",
        "state" => "NV",
        "address" => "522 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3542",
        "email" => "http://www.reid.senate.gov/contact/index.cfm",
        "website" => "http://www.reid.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "R000146",
        "leadership_position" => "Majority Leader"
      },
      {
        "member_full" => "Risch (R-ID)",
        "last_name" => "Risch",
        "first_name" => "James E.",
        "party" => "R",
        "state" => "ID",
        "address" => "483 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2752",
        "email" => "http://www.risch.senate.gov/public/index.cfm?p=Email",
        "website" => "http://www.risch.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "R000584"
      },
      {
        "member_full" => "Roberts (R-KS)",
        "last_name" => "Roberts",
        "first_name" => "Pat",
        "party" => "R",
        "state" => "KS",
        "address" => "109 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4774",
        "email" => "http://www.roberts.senate.gov/public/index.cfm?p=EmailPat",
        "website" => "http://www.roberts.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "R000307"
      },
      {
        "member_full" => "Rockefeller (D-WV)",
        "last_name" => "Rockefeller",
        "first_name" => "John D., IV",
        "party" => "D",
        "state" => "WV",
        "address" => "531 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6472",
        "email" => "http://www.rockefeller.senate.gov/public/index.cfm/email-jay",
        "website" => "http://www.rockefeller.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "R000361"
      },
      {
        "member_full" => "Rubio (R-FL)",
        "last_name" => "Rubio",
        "first_name" => "Marco",
        "party" => "R",
        "state" => "FL",
        "address" => "317 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-3041",
        "email" => "http://www.rubio.senate.gov/public/index.cfm/contact",
        "website" => "http://www.rubio.senate.gov",
        "class" => "Class III",
        "bioguide_id" => "R000595"
      },
      {
        "member_full" => "Sanders (I-VT)",
        "last_name" => "Sanders",
        "first_name" => "Bernard",
        "party" => "I",
        "state" => "VT",
        "address" => "332 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5141",
        "email" => "http://www.sanders.senate.gov/contact/",
        "website" => "http://www.sanders.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "S000033"
      },
      {
        "member_full" => "Schumer (D-NY)",
        "last_name" => "Schumer",
        "first_name" => "Charles E.",
        "party" => "D",
        "state" => "NY",
        "address" => "322 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6542",
        "email" => "http://www.schumer.senate.gov/Contact/contact_chuck.cfm",
        "website" => "http://www.schumer.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "S000148"
      },
      {
        "member_full" => "Sessions (R-AL)",
        "last_name" => "Sessions",
        "first_name" => "Jeff",
        "party" => "R",
        "state" => "AL",
        "address" => "326 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4124",
        "email" => "http://www.sessions.senate.gov/public/index.cfm?FuseAction=ConstituentServices.ContactMe",
        "website" => "http://www.sessions.senate.gov/",
        "class" => "Class II",
        "bioguide_id" => "S001141"
      },
      {
        "member_full" => "Shaheen (D-NH)",
        "last_name" => "Shaheen",
        "first_name" => "Jeanne",
        "party" => "D",
        "state" => "NH",
        "address" => "520 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2841",
        "email" => "http://www.shaheen.senate.gov/contact/",
        "website" => "http://www.shaheen.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "S001181"
      },
      {
        "member_full" => "Shelby (R-AL)",
        "last_name" => "Shelby",
        "first_name" => "Richard C.",
        "party" => "R",
        "state" => "AL",
        "address" => "304 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5744",
        "email" => "http://www.shelby.senate.gov/public/index.cfm/emailsenatorshelby",
        "website" => "http://www.shelby.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "S000320"
      },
      {
        "member_full" => "Snowe (R-ME)",
        "last_name" => "Snowe",
        "first_name" => "Olympia J.",
        "party" => "R",
        "state" => "ME",
        "address" => "154 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5344",
        "email" => "http://www.snowe.senate.gov/public/index.cfm/contact?p=email",
        "website" => "http://www.snowe.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "S000663"
      },
      {
        "member_full" => "Stabenow (D-MI)",
        "last_name" => "Stabenow",
        "first_name" => "Debbie",
        "party" => "D",
        "state" => "MI",
        "address" => "133 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4822",
        "email" => "http://www.stabenow.senate.gov/?p=contact",
        "website" => "http://www.stabenow.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "S000770"
      },
      {
        "member_full" => "Tester (D-MT)",
        "last_name" => "Tester",
        "first_name" => "Jon",
        "party" => "D",
        "state" => "MT",
        "address" => "724 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2644",
        "email" => "http://www.tester.senate.gov/Contact/index.cfm",
        "website" => "http://www.tester.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "T000464"
      },
      {
        "member_full" => "Thune (R-SD)",
        "last_name" => "Thune",
        "first_name" => "John",
        "party" => "R",
        "state" => "SD",
        "address" => "511 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2321",
        "email" => "http://www.thune.senate.gov/public/index.cfm/contact",
        "website" => "http://www.thune.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "T000250"
      },
      {
        "member_full" => "Toomey (R-PA)",
        "last_name" => "Toomey",
        "first_name" => "Patrick J.",
        "party" => "R",
        "state" => "PA",
        "address" => "502 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4254",
        "email" => "http://www.toomey.senate.gov/?p=contact",
        "website" => "http://www.toomey.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "T000461"
      },
      {
        "member_full" => "Udall (D-CO)",
        "last_name" => "Udall",
        "first_name" => "Mark",
        "party" => "D",
        "state" => "CO",
        "address" => "328 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5941",
        "email" => "http://www.markudall.senate.gov/?p=contact",
        "website" => "http://www.markudall.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "U000038"
      },
      {
        "member_full" => "Udall (D-NM)",
        "last_name" => "Udall",
        "first_name" => "Tom",
        "party" => "D",
        "state" => "NM",
        "address" => "110 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6621",
        "email" => "http://www.tomudall.senate.gov/?p=contact",
        "website" => "http://www.tomudall.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "U000039"
      },
      {
        "member_full" => "Vitter (R-LA)",
        "last_name" => "Vitter",
        "first_name" => "David",
        "party" => "R",
        "state" => "LA",
        "address" => "516 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4623",
        "email" => "http://www.vitter.senate.gov/public/index.cfm?FuseAction=Contact.ContactForm",
        "website" => "http://www.vitter.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "V000127"
      },
      {
        "member_full" => "Warner (D-VA)",
        "last_name" => "Warner",
        "first_name" => "Mark R.",
        "party" => "D",
        "state" => "VA",
        "address" => "475 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2023",
        "email" => "http://www.warner.senate.gov/public/index.cfm?p=Contact",
        "website" => "http://www.warner.senate.gov",
        "class" => "Class II",
        "bioguide_id" => "W000805"
      },
      {
        "member_full" => "Webb (D-VA)",
        "last_name" => "Webb",
        "first_name" => "Jim",
        "party" => "D",
        "state" => "VA",
        "address" => "248 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-4024",
        "email" => "http://www.webb.senate.gov/contact.cfm",
        "website" => "http://www.webb.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "W000803"
      },
      {
        "member_full" => "Whitehouse (D-RI)",
        "last_name" => "Whitehouse",
        "first_name" => "Sheldon",
        "party" => "D",
        "state" => "RI",
        "address" => "717 HART SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-2921",
        "email" => "http://www.whitehouse.senate.gov/contact/",
        "website" => "http://www.whitehouse.senate.gov/",
        "class" => "Class I",
        "bioguide_id" => "W000802"
      },
      {
        "member_full" => "Wicker (R-MS)",
        "last_name" => "Wicker",
        "first_name" => "Roger F.",
        "party" => "R",
        "state" => "MS",
        "address" => "555 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-6253",
        "email" => "http://www.wicker.senate.gov/public/index.cfm?FuseAction=Contact.EMailSenatorWicker",
        "website" => "http://www.wicker.senate.gov",
        "class" => "Class I",
        "bioguide_id" => "W000437"
      },
      {
        "member_full" => "Wyden (D-OR)",
        "last_name" => "Wyden",
        "first_name" => "Ron",
        "party" => "D",
        "state" => "OR",
        "address" => "221 DIRKSEN SENATE OFFICE BUILDING WASHINGTON DC 20510",
        "phone" => "(202) 224-5244",
        "email" => "http://www.wyden.senate.gov/contact/",
        "website" => "http://www.wyden.senate.gov/",
        "class" => "Class III",
        "bioguide_id" => "W000779"
      }
    ]
  end
end